# Default Configuration

# Grid
display_grid: 0

# Land
land_clr: "#E8E6E1"

land_data:
  0: "data/TM_WORLD_BORDERS-0.3.shp"
  3: "data/shoreline_300"
  7: "data/processed_p"

land_epsg:
  0: "init=epsg:4326"
  3: "init=epsg:3857"

# Water
waterarea_data:
  0: "geometry from (select geometry,osm_id ,OSM_NAME_COLUMN as name,type from OSM_PREFIX_waterareas_gen0) as foo using unique osm_id using srid=OSM_SRID"
  9: "geometry from (select geometry,osm_id ,OSM_NAME_COLUMN as name,type from OSM_PREFIX_waterareas_gen1) as foo using unique osm_id using srid=OSM_SRID"
  12: "geometry from (select geometry,osm_id ,OSM_NAME_COLUMN as name,type from OSM_PREFIX_waterareas) as foo using unique osm_id using srid=OSM_SRID"

display_waterarea_lbl:
  0:0
  6:1

waterarea_clr: "#B3C6D4"
waterarea_ol_clr: "#B3C6D4"
waterarea_ol_width: 0
waterarea_font: "sc"
waterarea_lbl_size: 8
waterarea_lbl_clr: "#6B94B0"
waterarea_lbl_ol_clr: "255 255 255"
waterarea_lbl_ol_width: 2
ocean_clr: "#B3C6D4"

display_waterways:
  0: 0
  6: 1

waterways_data:
  0: "geometry from (select geometry, osm_id, type, OSM_NAME_COLUMN as name from OSM_PREFIX_waterways_gen0 where type='river') as foo using unique osm_id using srid=OSM_SRID"
  9: "geometry from (select geometry, osm_id, type, OSM_NAME_COLUMN as name from OSM_PREFIX_waterways_gen1 where type='river') as foo using unique osm_id using srid=OSM_SRID"
  12: "geometry from (select geometry, osm_id, type, OSM_NAME_COLUMN as name from OSM_PREFIX_waterways) as foo using unique osm_id using srid=OSM_SRID"
  
canal_width:
  0: 0
  10: 0.5
  12: 1
  14: 2
  15: 4
  16: 8
  17: 16
  18: 30

display_canal_lbl:
  0: 0
  10: 1
canal_clr: "#B3C6D4"
canal_font: "sc"
canal_lbl_size: 8
canal_lbl_clr: "#6B94B0"
canal_lbl_ol_clr: "255 255 255"
canal_lbl_ol_width: 2

stream_width:
  0: 0,
  10: 0.5
  12: 1
  14: 2

display_stream_lbl:
  0:0
  12:1
  
stream_clr: "#B3C6D4"
stream_font: "sc"
stream_lbl_size: 8
stream_lbl_clr: "#6B94B0"
stream_lbl_ol_clr: "255 255 255"
stream_lbl_ol_width: 2

river_width:
  0: 0
  6: 0.15
  7: 0.25
  8: 0.5
  9: 1
  11: 2
  13: 3
  15: 4
  16: 5
  17: 6
  18: 7

display_river_lbl:
  0:0
  6:1
river_clr: "#B3C6D4"
river_font: "sc"
river_lbl_size: 
  0: 8
  15: 9
  17: 10
river_lbl_clr: "#6B94B0"
river_lbl_ol_clr: "255 255 255"
river_lbl_ol_width: 2

# Landuse

display_landusage:
  0:0
  4:1
   
landusage_data:
  0: >
    geometry from (select geometry ,osm_id, type, OSM_NAME_COLUMN as name from OSM_PREFIX_landusages_gen00) as foo 
    using unique osm_id using srid=OSM_SRID
  6: >
    geometry from (select geometry ,osm_id, type, OSM_NAME_COLUMN as name from OSM_PREFIX_landusages_gen0) as foo 
    using unique osm_id using srid=OSM_SRID
  9: >
    geometry from (select geometry ,osm_id, type, OSM_NAME_COLUMN as name from OSM_PREFIX_landusages_gen1 where 
    type in ('forest','industrial','commercial','residential')) as foo using unique osm_id using srid=OSM_SRID
  10: >
    geometry from (select geometry ,osm_id, type, OSM_NAME_COLUMN as name from OSM_PREFIX_landusages_gen1 
    where type in ('forest','pedestrian','cemetery','industrial','commercial',
    brownfield','residential','school','college','university','military','park','golf_course','grass','hospital','parking','stadium','sports_center',
    pitch') order by area desc) as foo using unique osm_id using srid=OSM_SRID
  12: >
    geometry from (select geometry ,osm_id, type, OSM_NAME_COLUMN as name from OSM_PREFIX_landusages 
    where type in ('forest','pedestrian','cemetery','industrial','commercial',
    brownfield','residential','school','college','university',
    military','park','golf_course','grass','hospital','parking','stadium','sports_center',
    pitch') order by area desc) as foo using unique osm_id using srid=OSM_SRID
industrial_clr: "#d1d1d1"
industrial_ol_clr: "#d1d1d1"
industrial_ol_width: 0
display_industrial_lbl:
  0:0
  11:1
industrial_font: "sc"
industrial_lbl_size: 8,
industrial_lbl_clr: "0 0 0"
industrial_lbl_ol_clr: "255 255 255"
industrial_lbl_ol_width: 2

residential_clr: "#E3DED4"
residential_ol_clr: "#E3DED4"
residential_ol_width: 0
display_residential_lbl: 
  0:0
  12:1
residential_font: "sc"
residential_lbl_size: 8
residential_lbl_clr: "0 0 0"
residential_lbl_ol_clr: "255 255 255"
residential_lbl_ol_width: 2

park_clr: "#DCDCB4"
park_ol_clr: "#DCDCB4"
park_ol_width: 0
display_park_lbl:
  0:0
  11:1
park_font: "sc"
park_lbl_size: 8
park_lbl_clr: "0 0 0"
park_lbl_ol_clr: "255 255 255"
park_lbl_ol_width: 2

hospital_clr: "#E6C8C3"
display_hospital_lbl:
  0:0
  12:1
hospital_font: "sc"
hospital_lbl_size: 8
hospital_lbl_clr: "0 0 0"
hospital_lbl_ol_clr: "255 255 255"
hospital_lbl_ol_width: 2

education_clr: "#DED1AB"
display_education_lbl:
  0:0
  12:1
education_font: "sc"
education_lbl_size: 8
education_lbl_clr: "0 0 0"
education_lbl_ol_clr: "255 255 255"
education_lbl_ol_width: 2
   
sports_clr: "#DED1AB"
display_sports_lbl:
  0:0
  12:1
sports_font: "sc"
sports_lbl_size: 8
sports_lbl_clr: "0 0 0"
sports_lbl_ol_clr: "255 255 255"
sports_lbl_ol_width: 2

display_cycleway_lbl:
  0:0
  12:1
cycleway_font: "sc"
cycleway_lbl_size: 8
cycleway_lbl_clr: "0 0 0"
cycleway_lbl_ol_clr: "255 255 255"
cycleway_lbl_ol_width: 2

display_pedestrian_lbl:
  0:0
  12:1
pedestrian_font: "sc"
pedestrian_lbl_size: 8
pedestrian_lbl_clr: "0 0 0"
pedestrian_lbl_ol_clr: "255 255 255"
pedestrian_lbl_ol_width: 2

cemetery_clr: "#d1d1d1"
display_cemetery_lbl:
  0:0
  12:1
cemetery_font: "sc"
cemetery_lbl_size: 8
cemetery_lbl_clr: "0 0 0"
cemetery_lbl_ol_clr: "255 255 255"
cemetery_lbl_ol_width: 2

forest_clr: "#C2D1B2"
display_forest_lbl:
  0:0
  12:1
forest_font: "sc"
forest_lbl_size: 8
forest_lbl_clr: "0 0 0"
forest_lbl_ol_clr: "255 255 255"
forest_lbl_ol_width: 2

display_transport_areas:
  0:0
  11:1
transport_clr: "200 200 200"
display_transport_lbl:
  0:0
  12:1
transport_font: "sc"
transport_lbl_size: 8
transport_lbl_clr: "0 0 0"
transport_lbl_ol_clr: "255 255 255"
transport_lbl_ol_width: 2

